language: php

# Start mysql service
services:
  - mysql

php:
  # - '5.6'
  - '7.0'
  # - '7.1'

sudo: true

ignore:
  - "vendor"
  
before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead;'
  - composer install --dev --prefer-source --no-interaction
  - php artisan key:generate
  - php artisan migrate --seed

script:
  - vendor/bin/phpmd app text codesize design naming unusedcode
  - vendor/bin/phpunit --testdox --coverage-text tests

notifications:
  email:
    recipients:
      - raza@xoho.tech
    on_success: always
    on_failure: always